modLoader = "javafml"
loaderVersion = "[10,)"
issueTrackerURL = "https://github.com/JPeisach/OneDot/issues"
license = "GNU General Public License v3.0"

[[mods]]
modId = "onedot"
version = "${version}"
displayName = "OneDot"
authors = "Joshua Peisach (JPeisach / ItzSwirlz)"
description = '''
Restores the "1." to the start of the Minecraft Client version number.
'''
logoFile = "icon.png"

[[dependencies.onedot]]
modId = "neoforge"
type = "required"
versionRange = "[21.10,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.onedot]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.10,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.onedot]]
modId = "architectury"
type = "required"
versionRange = "[18.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "onedot.mixins.json"
